HEIGHT = 1200
WIDTH =  1600

FALLINGSPEED = 2

FOLLOWDISTANCE = 300
MONSTERMAXSPEED = 3
MONSTERACCELERATION = 1
MONSTERSPEED = 3
MONSTERJUMP = 5

HEROSPEED = 10
HEROACCELERATION = 5
HEROMAXSPEED = 20
HEROJUMP = 50
HEROJUMPACCELERATION = 10

BLOCKWIDTH = 39
BLOCKHEIGHT = 54
