HEIGHT = 800
WIDTH =  1600

FALLINGSPEED = 1

FOLLOWDISTANCE = 500
MONSTERMAXSPEED = 8
MONSTERACCELERATION = 3
MONSTERSPEED = 5
MONSTERJUMP = 3
MONSTERJUMPACCELERATION = 10

HEROSPEED = 10
HEROACCELERATION = 5
HEROMAXSPEED = 20
HEROJUMP = 30
HEROJUMPACCELERATION = 20

BLOCKWIDTH = 39
BLOCKHEIGHT = 54
BLOCK_SIZE = 1

CAMERAOFFSET_X = 60
CAMERAOFFSET_Y = 0
